### ISSUE TITLE
YARN dist:win64 후 (페키징후)

### ISSUE THREAD

**Issue by danielinspring** [entrylabs/entry-offline#102]
페키징 전에는 HW 연결 프로그램에서 정상적으로 기기를 찾는데, 
YARN dist:win64 후 (페키징후) 에는 **" 하드웨어 연결에 실패했습니다. 연결을 재시도하거나 프로그램을 재실행해주세요."**
가 뜹니다. 제가 제작한 기기 말고 다른 기기연결시도를 하면 "하드웨어어와 연결을 시도하고있습니다." 가 뜨는데 제가 만든거는 연결되어있든 아니든, **" 하드웨어 연결에 실패했습니다. 연결을 재시도하거나 프로그램을 재실행해주세요."** 이 뜨네요

혹시 아직 기기 등록을 안한거라서 그럴가능성도 있을까요?  일단 페키징 전까지 yarn start 등을 했을때는 정상 동작을 합니다...

**Comment by wodnjs6512** [comment]
@danielinspring 
일단 릴리즈 되는 오프라인에 탑재되어있는 엔트리 하드웨어는 바이너리화 되어있어서 하드웨어 추가가 불가능합니다. 하드웨어 개발을 생각하고 있으시다면 https://entrylabs.github.io/docs/guide/ 를 참조하시는 것을 추천 드립니다.
