### ISSUE TITLE
[v2.0.18] 외부 vendor 관련 bower 디펜던시를 직접 파일 관리로 변경 이후의 가이드 문서가 있을까요

### ISSUE THREAD

**Issue by tjgmlfbs124** [entrylabs/entry-offline#104]
안녕하세요 저희는 최신버전의 Entry offline을 설치받아 빌드하려 합니다.

최신 프로젝트에는 bower.json이 없지만
https://entrylabs.github.io/docs/guide/entry-offline/2017-12-20-getting_started.html 

여기에서 제공하는 offline 가이드에서는 아직 최신화가 안되어있어서요!
작성된 문서가 있을까요

**Comment by JeongJun-Lee** [comment]
bower install 과정이 생략되었다 보시면 그냥 yarn 또는 npm install 한번만 수행하시면 됩니다.
