### ISSUE TITLE
블럭선택 메뉴 하단을 눌렀을 때, 에디터 창 전체가 밀려 올라가는 현상 

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#109]
버전: 2.0.31
OS: 윈도우즈

내용:  블럭선택 메뉴 하단을 눌렀을 때, 에디터 창 전체가 밀려 올라가는 현상으로 하단엔 회색 빈공간 생기며, 상단 메뉴공간은 끌어올려져 안보이는 현상
심각성: 맨 하단 블럭 카테고리인 하드웨어를 선택해 연결시도 마다 매우 불편을 야기함. 시급히 고쳐야 함.

![image](https://user-images.githubusercontent.com/11474775/108531308-5c3eaf80-72f8-11eb-8210-1299bb91797b.png)

**Comment by JeongJun-Lee** [comment]
v2.0.33 버전에도 여전히 발생하고 있으며, 윈도우즈에만 발생됨. reopen이 필요합니다!

**Comment by Neopia-Uz** [comment]
급하신 분은 해당 PR(https://github.com/entrylabs/entryjs/pull/2056) 을 사용하세요!

**Comment by JeongJun-Lee** [comment]
급하신 분은 해당 PR(https://github.com/entrylabs/entryjs/pull/2056) 을 적용하세요!
