### ISSUE TITLE
빌드결과물에 drivers, firmwares, modules 디렉토리가 두 번 중복되는데, 용량을 줄이기 위해 한번만 포함할 수 없는지?

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#115]
drivers, firmwares, modules 이상 3개의 디렉토리는 용량이 큰 편임에도 불구하고, 빌드 결과물에 중복 존재하는데 한 번으로 줄일 수 있는지요?

1. resources/app.asar.unpacked 밑에
2. resources/app.asar.unpacked/node_modules/entry-hw/app 밑에

**Comment by wodnjs6512** [comment]
https://github.com/entrylabs/entry-offline/commit/29e3117d6b275c36c5c88132388a0a4c889215b5
참조 부탁드립니다. 오프라인 다음 버전에 적용됩니다.
