### ISSUE TITLE
엔트리_우노 확장모드 업로드 에러

### ISSUE THREAD

**Issue by shkang770** [entrylabs/entry-offline#116]
첨부 파일과 같이 코딩했고 확장모드로 연결했는데 업로드가 안되네요.
![엔트리확장모드_부저1](https://user-images.githubusercontent.com/22616432/128013947-57e0e7c5-6a85-48e7-b607-b8444399530d.png)
![엔트리확장모드_부저2](https://user-images.githubusercontent.com/22616432/128013955-af260523-fb10-4684-939f-e060ecfd6d9f.png)

**Comment by JeongJun-Lee** [comment]
https://github.com/JeongJun-Lee/entry-offline/issues 에 올려져야 맞는 것으로 closed 처리 부탁드립니다.
