### ISSUE TITLE
오프젝트 중 일부가 오브젝트로 추가되지 않음

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#120]
v2.0.37버전에서 해당 오프젝트를 추가하면 추가되지 않는데, 

![image](https://user-images.githubusercontent.com/11474775/132093164-f5556170-97cd-4b76-9bfc-01d8eff7c3ef.png)

![image](https://user-images.githubusercontent.com/11474775/132093341-1e321d3c-67b7-4828-9ae6-fef0ece5b49a.png)

sprites.js에 filename에 실제 파일이 존재하지 않음.
"ko":"배터리(1)_70%"},"dimension":{"width":348,"height":176},"filename":"4c20f33a95cbad321cdcc38fcb1dd281","name":"배터리(1)_70%"}

**Comment by Tnks2U** [comment]
#126 에서 처리하였습니다.
