### ISSUE TITLE
error Couldn't find match for "2391c65135a87b0088e75d332cc4ed2959545809"

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#130]
yarn install 에서 에러 나서 설치할 수 없습니다.  packages.jon 안에 
"entry-tool": "git+https://github.com/entrylabs/entry-tool.git#dist/develop", 에서 에러발생합니다.

[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find match for "2391c65135a87b0088e75d332cc4ed2959545809" in "refs/heads/11275-3,refs/heads/build,refs/heads/develop,refs/heads/develop-hw,refs/heads/develop2,refs/heads/dist/develop,refs/heads/dist/develop-hw,refs/heads/dist/develop2,refs/heads/feature/datavisualize_tracker,refs/heads/feature/dropdown_extra_fix,refs/heads/feature/entry-paint,refs/heads/feature/magnify,refs/heads/feature/rollup,refs/heads/issue/11512_6,refs/heads/issue/11561,refs/heads/issue/12217_mouse_over,refs/heads/issue/12272_lang,refs/heads/issue/12276,refs/heads/issue/12277,refs/heads/issue/12289,refs/heads/issue/12292,refs/heads/issue/12297,refs/heads/issue/12308,refs/heads/issue/12312,refs/heads/issue/12313,refs/heads/issue/12314,refs/heads/issue/12317,refs/heads/issue/12320,refs/heads/issue/12320_reopen,refs/heads/issue/12321,refs/heads/issue/12323,refs/heads/issue/12324,refs/heads/issue/12325,refs/heads/issue/12328,refs/heads/issue/12329,refs/heads/issue/12331,refs/heads/issue/12333,refs/heads/issue/12333_reopen,refs/heads/issue/12334,refs/heads/issue/2063,refs/heads/issue/2564,refs/heads/issue/276_HistogramMarkup,refs/heads/issue/3058,refs/heads/issue/315,refs/heads/issue/WsRenewalMarkup/3503,refs/heads/issue/microbit2,refs/heads/issue2/1860,refs/heads/issue2/2090,refs/heads/issue2/2231,refs/heads/issue2/2902,refs/heads/master,refs/heads/production,refs/heads/snapshot/entry-tool-20190320,refs/heads/web-serial,refs/tags/v1.1.8,refs/tags/v1.20180817.1,refs/tags/v1.20180817.2,refs/tags/v1.20180905.3,refs/tags/v1.20180905.4,refs/tags/v1.20180911.5,refs/tags/v1.20190401.152,refs/tags/v1.20190411.153,refs/tags/v1.20190415.154,refs/tags/v1.20190503.155,refs/tags/v1.20190527.156,refs/tags/v1.20190530.157,refs/tags/v1.20190625.158,refs/tags/v1.20190722.159,refs/tags/v1.20190819.160,refs/tags/v1.20190909.161,refs/tags/v1.20190910.162,refs/tags/v1.20190910.163,refs/tags/v1.20190916.164,refs/tags/v1.20190916.165,refs/tags/v1.20190923.166,refs/tags/v1.20190923.167,refs/tags/v1.20190924.168,refs/tags/v1.20190924.169,refs/tags/v1.20190924.170,refs/tags/v1.20190924.171,refs/tags/v1.20190925.172,refs/tags/v1.20190925.173,refs/tags/v1.20190925.174,refs/tags/v1.20190926.175,refs/tags/v1.20191014.176,refs/tags/v1.20191015.177,refs/tags/v1.20191120.178,refs/tags/v1.20191125.179,refs/tags/v1.20191202.180,refs/tags/v1.20191202.181,refs/tags/v1.20191213.182,refs/tags/v1.20191226.183,refs/tags/v1.20200103.184,refs/tags/v1.20200114.185,refs/tags/v1.20200115.186,refs/tags/v1.20200121.187,refs/tags/v1.20200121.188,refs/tags/v1.20200214.189,refs/tags/v1.20200218.190,refs/tags/v1.20200218.191,refs/tags/v1.20200218.192,refs/tags/v1.20200218.193,refs/tags/v1.20200219.196,refs/tags/v1.20200220.197,refs/tags/v1.20200220.198,refs/tags/v1.20200220.199,refs/tags/v1.20200220.200,refs/tags/v1.20200220.201,refs/tags/v1.20200221.202,refs/tags/v1.20200221.203,refs/tags/v1.20200221.204,refs/tags/v1.20200226.205,refs/tags/v1.20200226.206,refs/tags/v1.20200226.207,refs/tags/v1.20200323.208,refs/tags/v1.20200324.209,refs/tags/v1.20200326.210,refs/tags/v1.20200326.211,refs/tags/v1.20200330.212,refs/tags/v1.20200413.213,refs/tags/v1.20200413.214,refs/tags/v1.20200414.215,refs/tags/v1.20200414.216,refs/tags/v1.20200416.217,refs/tags/v1.20200416.218,refs/tags/v1.20200424.219,refs/tags/v1.20200428.220,refs/tags/v1.20200525.221,refs/tags/v1.20200528.222,refs/tags/v1.20200617.223,refs/tags/v1.20200629.224,refs/tags/v1.20200807.225,refs/tags/v1.20200825.226,refs/tags/v1.20200923.227,refs/tags/v1.20201105.228,refs/tags/v1.20201106.229,refs/tags/v1.20201125.230,refs/tags/v1.20201231181843.3,refs/tags/v1.20201231200210.4,refs/tags/v1.20210104161056.5,refs/tags/v1.20210104202248.6,refs/tags/v1.20210104210555.7,refs/tags/v1.20210104223427.8,refs/tags/v1.20210107113246.9,refs/tags/v1.20210107172953.10,refs/tags/v1.20210107174546.11,refs/tags/v1.20210107182721.14,refs/tags/v1.20210111202954.15,refs/tags/v1.20210113143655.17,refs/tags/v1.20210114142646.19,refs/tags/v1.20210225104253.1,refs/tags/v1.20210225151736.2,refs/tags/v1.20210226105636.3,refs/tags/v1.20210318110641.4,refs/tags/v1.20210512005741.5" for "https://github.com/entrylabs/entry-tool.git".

**Comment by Tnks2U** [comment]
안녕하세요. 확인이 늦었습니다.
entry-tool의 의존성 문제일수 있으니 yarn.lock 파일에 entry-tool 부분만 삭제하시고 새로 yarn 명령어로 패키지들을 받아보시는건 추천드립니다.

**Comment by JeongJun-Lee** [comment]
이게 그렇게 했더니 side-effect이 있네요; 아직, 웹에디터에만 적용하신 태블릿, 스마트폰 대응 신규 ui가 offline쪽 빌드에도 딸려왔고, 문제는 전엔 문제없던 버튼에 번역이 다음과 같이 깨져버리네요;

![image](https://user-images.githubusercontent.com/11474775/155406656-f89be0cd-ebdb-4f2a-ada1-53fc60f464ba.png)

기존에는 ko.json파일에 Lang.Buttons 안에 있는 add: "추가" 라는 부분을 각 언어에서 번역하면 되던 것인데, 저건 어떤 신규번역이지요?

**Comment by Tnks2U** [comment]
@JeongJun-Lee 
안녕하세요.
말씀주신대로 현재 오프라인에서 다국어 작업이 완료되지 않은 사용성개선 버전이 적용된것으로 보입니다.
오프라인에서 사용성 개선은 다국어 작업을 마치고 배포될 예정이므로 우선은 예전 버전 사용을 위해 yarn.lock 파일에 entry-tool관련 dependancy를 아래와 같이 수정해주시기 바랍니다.(현재 운영버전에서 사용중인 버전입니다.)

```
"entry-tool@git+https://github.com/entrylabs/entry-tool.git#dist/develop":
  version "0.0.0"
  resolved "git+https://github.com/entrylabs/entry-tool.git#302c3d6649fd56c5665e1fbe3a30b1ec309fece0"
```

yarn.lock 파일을 수정 후 'yarn' 명령어로 모듈설치&rebuild 를 완료하시고 테스트해보시면 운영환경과 동일하게 적용될것으로 보입니다.

**Comment by JeongJun-Lee** [comment]
안녕하세요?

아쉽게도 알려주신 방법으로 해결이 안되네요. 혹시나 하고, ko.json에 add2: "추가" 라고, 임의로 add2라는 걸 추가했더니, 그걸 인식해 번역이 되긴 하네요. 현재로선 다른 방법이 없으니 당장은 임기응변으로 이렇게 대응 수 밖에 없겠네요.

**Comment by Tnks2U** [comment]
말씀대로 다국어를 적용시킨 entry-tool 개선버전을 정기배포 및 github에 업로드 전까지는, 우선 개발하시는 작업에 문제가 없으시다면 말씀대로 사용하시는게 좋을 것 같습니다.

혹시 개발중에 entry-tool을 구버전으로 되돌리고 싶으시다면 package.json의 entry-tool 타깃을 develop브랜치가 아닌 아래 태그들 중 원하는 날짜로 세팅하시면 될 것 같습니다.(사용성 개선 전 버전은 대략 8개월 전입니다.)
https://github.com/entrylabs/entry-tool/tags

**Comment by JeongJun-Lee** [comment]
네 기다리도록 하겠습니다!
