### ISSUE TITLE
yarn install 에러

### ISSUE THREAD

**Issue by sonkee77** [entrylabs/entry-offline#132]
아래 같이 에러가 나서 설치가 안되고 있습니다.??

error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://8a14b1ce074335d7a7d9099b4a0807cc40fc9434:x-oauth-basic@oss.navercorp.com/ria/entry_sheet.git
Directory: D:\git\entry-offline
Output:
fatal: unable to access 'https://oss.navercorp.com/ria/entry_sheet.git/': Could not resolve host: oss.navercorp.com
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by Tnks2U** [comment]
안녕하세요.
entry_sheet 모듈을 로드하는데 문제가 발생한 것으로 보입니다. 
entry_sheet은 일반git이 아닌 사내git에 있는 레포지토리이기 때문에 빌드된 entry-tool모듈에서 포함한 형태로 제공됩니다. 외부에서 직접적으로 불러올 수 없습니다.

entry-offilne 내에서 직접적으로 entry_sheet을 로드하는 코드가 없고, 일반사용자 환경에서도 master기준으로는 정상적으로 설치가 되는 것을 확인하였습니다.

브랜치를 master로 최신화한 뒤 node_modules 디렉토리를 삭제하고 다시 설치시도를 해보시길 권장합니다.
이후에도 같은 문제가 발생한다면, 레포지토리 전체 검색에서 entry_sheet 의존성이 있는지 확인 부탁드립니다.
