### ISSUE TITLE
오브젝트_여러 모양중 화살표 모양 이미지 사라지는 현상

### ISSUE THREAD

**Issue by baxtiyor8291** [entrylabs/entry-offline#133]
오브젝트중 모양 이미지가 계속적으로 사라집니다. 화살표 모양을 불러와서 정상적으로 사용하고 저장하면 계속 유지되나
다음날 저장된 파일을 열면 그림과 같이 모양 이미지가 사라져 있습니다.

https://drive.google.com/file/d/1LNG6PbobXrAqEWbJzz3T0G3dt0IIpara/view?usp=sharing

**Comment by JeongJun-Lee** [comment]
안녕하세요? 이 이슈는 혹시 해결이 되었는지 궁금합니다. 엔트리 웹사이트 공지사항 4월 업데이트(https://playentry.org/community/notice/608a906c1eb58a00197cf305) 수정내역에 아래와 같이 유사성이 있는 수정내역에 대한 언급이 있습니다.

19. 오프라인 작품을 불러와서 온라인에 저장해도 작품의 썸네일이 잘 표시되도록 수정했어요.

왜냐면 저희가 의심했던 내용도 추후 작품불러오기 로딩시에 생기는 문제라기 보다 애시당초 작품저장시에 잘못저장된 문제로 봤었기 때문입니다.
암튼 그래서 결론적으로 저 수정내역을 저희버전에도 cherry-pick하고 싶은데요.  2022년 3-4월 부근에 commit list를 아무리 봐도 저것 관련해 수정된 커밋이 무엇인지를 전혀 모르겠습니다. 커밋메시지들에 엔트리팀 내부에서 관리하시는 외부 공개 하지 않으시는 별도 이슈리스트가 있으신 것 같은데, 그 이슈번호만 남기고 커밋메시지를 끝내버려서 도저히 무슨 사유로 수정된 것인지 저희는 전혀 알 수가 없습니다;;;
