### ISSUE TITLE
[이슈] 블록 이미지 저장하기 안됨

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#178]
버전: 2.1.0
증상: 아래와 같이 블록을 이미지로 저장하기하면 파일이름 설정하는 팝업이 뜨지 않음

<img width="231" alt="image" src="https://user-images.githubusercontent.com/11474775/222277564-53c50ab2-6bb7-4cb8-beba-922445b3b974.png">

**Comment by Tnks2U** [comment]
2.1.1 부터 블럭메뉴에서도 저장이 가능하도록 수정되었습니다.
