### ISSUE TITLE
인공지능 모델학습하기 블럭지원 여부

### ISSUE THREAD

**Issue by giyeonkwon** [entrylabs/entry-offline#183]
안녕하세요?
기능지원과 관련해서 문의드리려고 이슈 남깁니다.
혹시 "인공지능 모델학습하기" 블럭은 entry-offline에서 지원예정인지 궁금합니다.

감사합니다.

![image](https://github.com/entrylabs/entry-offline/assets/30770570/7764fd85-594b-48b7-b0fd-5c5f3dcb2e9f)

**Comment by JeongJun-Lee** [comment]
저는 궁금함을 넘어 이곳 개도국에서의 AI 교육을 위해서 매우!! 필요합니다ㅠ
소스코드 검토해보니, 인터넷만 연결되어 있다면, 오프라인 버전에서도 불가능해보이지 않던데요. 다만, entry-ml 관련 코드가 오픈소스가 아니라, 폐쇄소스로 공개를 안해주고 계셔서 외부에선 개발할 방법이...
