### ISSUE TITLE
엔트리 오프라인에는 부스터모드가 없으므로 판단블록 안에 부스터모드 on/off 판별블록의 제거필요

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#197]
엔트리 오프라인에는 부스터모드가 없으므로 판단블록 안에 부스터모드 on/off 판별블록의 제거필요

**Comment by ADev531** [comment]
엔트리 오프라인으로 만든걸 온라인으로 올릴수도 있는거 아닌가요??

**Comment by JeongJun-Lee** [comment]
사용자의 UX를 고민해볼 필요가 있습니다. 오프라인에서 저 기능이 제대로 동작하는지 검증하지 못한체 일단 예상 코딩을 한 후,  파일 저장 후(오프파인에서 직접 온라인으로 올릴 순 없기 때문에), 이후 온라인 사이트에 가서 저장된 파일(.ent)을 온라인으로 올리고 그제서야 기능검증을 해본다? 뭐 그렇게까지 하려는 분이 있다면 놔둘 수도 있겠습니다.

**Comment by ADev531** [comment]
지금보니 EntryJS에도 없네요. ENTRYJS에 부스터모드 추가해달라고 이슈 올리는게 나은듯 합니다.
