### ISSUE TITLE
안녕하세요? 오프라인 버전에 로드맵을 알고 싶습니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#44]
안녕하세요? 개도국에 봉사요원으로 일하고 있습니다.

이곳 개도국에서 엔트리를 활용해 보고 싶어서요. 그런데 아시다시피 개도국에 인터넷 상황이 매우 열악해서 오프라인 버전은 반드시! 필수입니다. 제가 혹 여유가 된다면 오프라인 버전에 이곳 개도국에 지역화를 위해 도움이 될만한 것들을 추가 개발해보고 싶은 의향이 있기도 하구요. 그런데, 최근에 다시 왔더니 오프라인 버전 개발에 참여할 수 있게 되어있던 문서화 내용이 다 사라졌네요? 혹시 엔트리쪽에서 오프라인 버전에 대한 지원이 중단되는지요? 
장기적으로 어떤 로드맵을 갖고 계신지 궁금합니다. 저는 개인적으로는 저희 나라의 자랑스런 코딩교육용 툴이 세계적으로도 특별히 개도국 어린이들을 위해서 쓰이면 좋겠는데 그러자면 오프라인 버전에 대한 지원이 더 많이 되어야 할 것으로 보이구요.  엔트리 개발팀의 의견을 듣고 싶습니다.

감사합니다.

**Comment by Kyunggyuil** [comment]
안녕하세요 늦은 답변에 죄송합니다.

오프라인 버전에 대한 지원은 중단되지 않습니다.
개발 관련 문서는 현재 최신 버전의 내용으로 변경되었으며, 해당 내용은 다음의 링크에서 확인이 가능합니다.
https://entrylabs.github.io/docs/

아울러 현재 최신버전의 오프라인은 1.5.1 인점 참고를 부탁드립니다.

**Comment by JeongJun-Lee** [comment]
답변 감사합니다. 추가 질문이 있습니다.
개도국에서 아이들 교육용으로 노트북이나 PC환경이 여의지 않아, 태블릿을 활용하면 좋겠는데요.
잘 아시겠지만, 인터넷 역시도 원활하지 않아 태블릿용 오프라인 버전이 필요한데요. 혹시 현재 시점에서 가능한 방법이나 없다면 추후 개발 계획이 있으신지요?

**Comment by Kyunggyuil** [comment]
태블릿 중 windows OS를 사용하는 경우 현재 제공되고 있는 오프라인 버전을 설치하여 이용할 수 있습니다.
하지만, iOS 또는 Android 등의 경우에 대해서는 오프라인 버전의 설치 및 이용이 불가능합니다.
아울러 추후 지원을 위한 검토가 이루어질 예정이며 아직까지 구체적인 지원 목표 일정 및 지원 범위에 대해서는 확정된 바가 없어 말씀을 드릴 수 없는 점 양해를 부탁드립니다.

추가 문의가 있으신 경우 entry@connect.or.kr 로 문의 주시길 바라며, 본 이슈는 클로징을 부탁드립니다.
감사합니다.
