### ISSUE TITLE
지역어 번역 관련 문의

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#46]
안녕하세요?

제가 개인적으로 이곳 지역어 번역을 시작해 보려고 합니다. 소스를 살펴보니 /extern 디렉토리 안에 지역어 번역이 추가되는 것으로 보입니다. 참고하려고 베트남어 번역인 vs.js 를 열어봤는데요. 전체가 다 베트남어는 아니고 파일에 일정 부분이 번역된 것으로 보입니다. 
저 역시도 번역을 목표로 하는 부분은 엔트리 웹사이트 내용에 대한 것은 아니고, 오프라인 버전용에 한정된 내용과 엔트리와 연결해 코딩이 가능한 특정 외부 하드웨어가 아닌 범용 하드웨어, 예를들면 아두이노 연결 활용 부분까지만 번역을 해보고 싶은데요. 
그렇다면 하고자 한다면, 예를들어 ko.js 파일 안에 어떤 부분까지만 번역하면 되는지 가이드를 주시면 좋겠습니다. 
 
감사합니다.

**Comment by kimorkim** [comment]
@JeongJun-Lee 
안녕하세요.
일단 오프라인 프로그램의 경우 현재는 몇몇부분이 엔트리 온라인 코드에 기대는 부분이 많이 존재하는 상태입니다.
대표적으로 다국어 부분도 그러한 상황인데요.
현재 제공되고 있는 다국어파일이 온라인과 오프라인이 공용으로 사용하는 파일입니다.
때문에 온오프라인 구분없이 사용되고 있습니다.
불편하시겠지만 현재로선 일일이 코드에서 사용되고 있는 다국어를 보시고 판단하실 수밖에 없습니다.
앞으로 이부분도 개선을 진행하여 보다 수월하게 다국어지원을 할수 있도록 노력하겠습니다.

**Comment by JeongJun-Lee** [comment]
네 당장은 업무 우선 순위로 작업을 못하시는 것 같지만, 궁극적으로 오프라인 버전과 온라인 버전은 번역 파일 분리가 되어 다양한 다국어 버전이 손쉽게 제작될 수 있는 환경을 만들어 주시면 좋겠네요. 그럼 전 오프라인 버전에 문서화가 완료 되기까지 기다리면서 우선은 틈틈이 지역어 번역을 먼저 시작해야겠네요. 감사합니다.

**Comment by JeongJun-Lee** [comment]
안녕하세요? 

현재 오프라인 버전과 온라인 버전에 파일 분리가 되어있지 않아서, 할 수 없이 vn.js 파일 안에 베트남어로 번역된 부분 위주로 먼저 번역을 시도해보고 있습니다. 문제는 번역한 내용이 프로그램에 잘 반영 되는지 가끔 확인해가며 번역을 해야하는데, 빌드에 대한 문서화를 내년 일월 중에나 작업이 가능하다 하셔 그때까지 기다릴 순 없어서 우선은 나름대로 편법이지만 찾아서 번역 검증을 해보려고 애쓰는 중입니다. 하지만 이것도 생각만큼 쉽게 되지는 않네요; 그것과 관련해 문으드립니다.

먼저, 제 PC는 맥OS 환경이고 오프라인 버전 설치 후 설치 경로에 있는 asar 파일을 압축해제 후 src/rederer/lang/vn.js 파일 안에 특정 단어 예를 들어 "add_object": "thêm đối tượng" 를 임의의 단어로 변경 후 앱을 구동해 보았습니다. 그런데, 제가 바꾼 내용이 앱에 전혀 반영이 안되더라구요. 어떤 이유일까 생각해보다가 혹시 캐시가 남아있어서 그런가 싶어, 앱에 관련한 캐시가 위치한 경로를 찾아서 지워봤습니다. 그래서, 계속 수정 내용이 반영이 안됩니다. 

제가 문서화가 완료되기 전까지 번역 검증 작업을 어떻게 해나갈 수 있을까요?
감사합니다.

**Comment by kimorkim** [comment]
asar에 파일을 주입시키면 변경이 되는것은 맞으나
저희가 사용하는 프레임워크가 electron-forge라는 것인데 asar로 패키징 이전에 electron-compile이 일종의
cached compile 을 수행합니다. 이 컴파일 과정은 사람이 수행할수 없는 과정으로 이미 패키지 되어나간 프로그램을 재 수정하는것은 어렵습니다.
오프라인 프로그램이 electron-forge를 기반으로 만들어 졌으므로 electron-forge를 사용하여 테스트 
하시는것이 제일 좋습니다.
https://github.com/electron-userland/electron-forge
위의 레포지토리에 가면 electron-forge의 사용법이 나와있습니다.

**Comment by JeongJun-Lee** [comment]
도움에 감사합니다. electron-forge 를 사용해 build하는데까지 성공했습니다^^ 다만, 릴리즈 버전을 만들기 위한 electron-forge make 나 publish 에 경우, 다음과 같은 에러가 발생합니다.

An unhandled error has occurred inside Forge:
ENOENT: no such file or directory, stat '/var/folders/9d/vq1v6bv94wb25wvhg34lr44h0000gp/T/electron-packager/darwin-x64/Entry-darwin-x64/Electron.app/Contents/Resources/app/.bowerrc'

**Comment by kimorkim** [comment]
publish 같은 경우는 저희도 사용하지 않는 상태이고,
작성 해주신 오류와 같은 경우는 정보가 너무 부족한 상태입니다.
좀더 상세한 로그가 있어야 알수 있으며, 저희가 electron-forge의 내부 이슈까지는 알기 쉽지 않은 상태입니다.

상세한 디버그 로그는 보는 방법은 환경변후 DEBUG 값에 *를 세팅하는것이 제일 많은 로그를 확인 가능합니다.
![image](https://user-images.githubusercontent.com/5179851/34374977-7b39eb36-eb27-11e7-90e7-d086576571cc.png)
오프라인 package.json 파일을 보시면 dev 항목에 위의 그림처럼 작성되어 있는데요 make부분에 대한 옵션을 추가해 주시고
`yarn make`또는 `npm run make` 를 수행해 보시기 바랍니다.

**Comment by JeongJun-Lee** [comment]
감사합니다. 제가 electron-forge make 라고, 직접 명령을 주었을 땐 에러가 나던데 npm run make 로는 에러없이 잘 릴리즈 버전이 생성되었습니다^^ 다만, 릴리즈 버전을 실행시키자마자 나면 다음과 같이 Main process 에서 electoron-compile 모듈을 찾을 수 없다는 에러가 납니다.
![image](https://user-images.githubusercontent.com/11474775/34375559-f602076e-eb08-11e7-94ce-b8d32f73b879.png)

**Comment by kimorkim** [comment]
혹시 의존성 모듈을 전부 설치해 주셨나요? electron-compile이 설치 되지 않은것으로 보입니다.

**Comment by JeongJun-Lee** [comment]
electron-compile 의존성 모듈은 설치되어 있습니다. 인터넷 검색을 해보니 https://github.com/electron-userland/electron-forge/issues/277 와 https://github.com/electron-userland/electron-forge/issues/249 에 yarn 과 npm 버전 사이에 패키지 관리 문제가 있어 발생하는 것으로 추측됩니다.

**Comment by kimorkim** [comment]
엔트리개발팀에서 오프라인 및 하드웨어를 관리할때는 `yarn`을 사용합니다. 참고 부탁드립니다.

**Comment by JeongJun-Lee** [comment]
위에 electron-forge 이슈 리스트에 언급된데로 npm 버전은 3.x로 다운그레이드 해서 해보니 빌드 버전에 에러가 사라졌습니다. 그럼, 이제 번역 작업에 속도를 낼 수 있겠네요^^ 새해 복 많이 받으시구요! 나중에 문의 사항 생기면 또 찾아오겠습니다. 감사합니다.
