### ISSUE TITLE
커스텀 컨텐트(오브젝트)를 제작하는 가이드를 좀 알 수 있을까요?

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#47]
안녕하세요?

이곳 개도국에 지역어 버전을 만들려는 준비를 구체화 하면서 관련해 계속 문의가 생기네요^^; 제목에 문의 드린 바와 같이 이곳 국가의 전통 복장의 오브젝트 같은 것을 몇 개 만들어 추가해 배우는 아이들에게 친숙하게 다가갈 수 있도록 하려고 합니다. 오브젝트 제작에 가이드를 좀 제공해 주실 수 있으실까요? 이미지 파일에 크기와 해상도라든지 표준화된 규격을 가지고 계실 것 같아서요. 그리고, 제작 후 어느 디렉토리에 위치시켜야 로딩이 가능할런지요?

감사합니다.

**Comment by kimorkim** [comment]
@JeongJun-Lee 
오프라인기준으로 설명 드리면 일단 image는 특별한 기준은 없이 png파일입니다.
다만, 용량을 최소화 하기 위해 이미지 압축 및 최적화를 진행합니다.
(저희쪽에서 주로 사용하는 툴은 [tinypng](https://tinypng.com/)입니다.)
image가 있으면 thumb(썸네일) 이미지도 필요합니다. 썸네일 이미지의 경우는 96*96 사이즈를 가지고 있습니다.

오브젝트를 추가하기 위해선는 resouce_map의 json파일을 먼저 수행해야 합니다.
기본적으로 엔트리에서는 관리되는 오브젝트들은 내부적으로 사용되는 어드민 툴을 이용해서만 업로드가 가능하고
해당 업로드시에 아이디가 발급되고 있습니다.
오프라인에서 별개로 picture를 추가 한다면 picture.json에 해당값을 직접 입력하여햐 합니다.
기존데이터와 겹치지 않는 새로운 값을 추가하시면 되며, 여기서 가장 중요한내용은 filename입니다.
해당 파일네임의 앞글개 4글자를 자르고 다시 2글자씩 잘라서
uploads폴더의 경로로 활용됩니다

예) 파일이름이 1b4a6612a522d02fa2e69611bd2925e3 인 경우
uploads/1b/4a 폴더 및에 image폴더와 thumb 폴더가 존재하고 각각 1b4a6612a522d02fa2e69611bd2925e3.png 라는 이름으로 그림파일이 존재함.

위와 같이 작업이 이루어 집니다.
어느 카테고리에 나오게 할지는 category 필드 작성에 따라 나오는 위치가 변경하게 됩니다.

**Comment by JeongJun-Lee** [comment]
감사합니다. 그런데, 언급하신 uploads 폴더를 어디에서도 찾을 수 없는데요? 이곳 리포지토리에도 윈도우즈 버전과 맥 버전 오프라인 앱을 설치 후 설치된 디렉토리 안에도 어디에서도 찾지 못했는데요;;; 어디에 있는 것일까요?

**Comment by kimorkim** [comment]
@JeongJun-Lee 설치 이후에는 패키징 되서 찾을수가 없고 
레포지토리에서는 
![image](https://user-images.githubusercontent.com/5179851/33982627-81d55288-e0f4-11e7-922a-3298e8360f31.png)
위 스크린샷의 위치에 있습니다.

**Comment by JeongJun-Lee** [comment]
node_modules 안에 있었군요. 그럼, 우선은 이슈를 닫겠습니다. 해보다가 또 해당 내용에 대해 다시 문의가 생기면 그때 재오픈 하겠습니다. 늘 도움에 감사드립니다^^

**Comment by JeongJun-Lee** [comment]
참고로 다른 분들에게 도움이 되기 위해 남깁니다. sprites.json 에도 추가되어야 합니다.

**Comment by JeongJun-Lee** [comment]
만약 오브젝트 상에 표기되는 이름이 한글로 보이길 원지 않으시면 sprites.js에도 내용을 추가해야 합니다.
