### ISSUE TITLE
Mac OS  매버릭스에서 하드웨어 연결 관련 윈도우가 그냥 하얀 바탕 창이고 아무 표시가 나타나지 않습니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#50]
안녕하세요? 이슈 리포트 합니다.

블록메뉴에서 하드웨어 -> 연결 프로그램 열기 -> 하드웨어 선택에서 어떤 하드웨어를 선택하든지 그 다음 뜨는 하드웨어 연결 관련 윈도우가 그냥 하얀 바탕 창이고 아무 표시가 나타나지 않습니다.

오프라인 1.6.1 버전이고,  Mac OS 매버릭스 버전입니다.

감사합니다.

참고로 Mac OS 시에라 버전에서는 문제 없습니다.

**Comment by kimorkim** [comment]
안녕하세요.
일단 해당 이슈는 오프라인문제는 아니고 하드웨어 문제인것으로 보입니다.
일렉트론의 경우 10.9(매버릭스) 부터 지원을 하지만, 
저희가 사용한 다른 라이브러리가 지원을 못하는 경우 인것으로 보입니다.
이경우 디버깅을 통해 어디서 오류가 발생하는지 확인을 해야 하는데
저희가 보유한 mac중에 현재 매버릭스 버전이 없어서 확인이 힘든상태입니다.
아무래도 해당 문제 확인에는 상당한 시간이 걸릴것 같습니다.

**Comment by kimorkim** [comment]
@JeongJun-Lee 
안녕하세요.
매버릭스 오류관련 테스트중에 있습니다.
혹시 해당 오류가 컴퓨터에 연결 가능한 serial 장치가 연결되어 있는 상태인가요?

현재 저희가 사용하는 serialport 라이브러리가 연결 가능한 장치가 없을 때 exception 이 
발생하는것같아서 문의 드립니다.

아무래도 저희가 관리하는 코드가 아닌 사용하는 라이브러리에서 발생하는 오류가 확인이 좀 힘든 부분이 있습니다.

**Comment by JeongJun-Lee** [comment]
앱 실행시 아무 장치도 연결되어 있지 않고, 심지어 usb 포트나 블루투스에도 어떤 장치도 연결되어 있지 않은 깨끗한 상태서 발생합니다.

**Comment by kimorkim** [comment]
@JeongJun-Lee 
내용 확인 했습니다.
아마 다음 하드웨어 패치 때 하드웨어에 적용될 수 있을것 같습니다.
오프라인의 경우 패치가 매번 한박자 느리게 패치가 되고 있어 오프라인 정식버전은 다다음 버전에 해당
문제가 해결 될것 같습니다.

**Comment by kimorkim** [comment]
관련 내용 수정되어 close 처리 합니다.
