### ISSUE TITLE
package.json에 devDependencies안에 이상한 내용이 있는 것같습니다.

### ISSUE THREAD

**Issue by hhgyu** [entrylabs/entry-offline#51]
package.json안에 devDependencies 파트에 있는 옵션 중에 아래와 같은 내용이 추가 되어있습니다.
`
    "rebuild": "electron-rebuild -v 1.7.8",
`
npm install 시에

npm ERR! code ETARGET
npm ERR! notarget No matching version found for electron-rebuild@1.7.8
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'entry'
npm ERR! notarget

와 같은 내용이 출력되면서 동작을 하지 않아서 찾아보니 electron-rebuild의 경우 1.7.2까지 밖에 출시가 되지 않은 것으로 보이고 있습니다.

해당 내용이 없더라도
`
    "electron-rebuild": "^1.6.0",
`

이 내용이 있는 것으로 봐서는 뭔가가 잘못되지 않았나 싶습니다.

**Comment by kimorkim** [comment]
`decpendencies` 내용이 아닌게 들어가 있었네요. 정보 감사합니다.
저희 같은 경우는 `npm`을 사용하지 않고 `yarn`을 사용해서 발생하지 않는 오류 였습니다.
