### ISSUE TITLE
entry-offline을 사용할 때에도 하드웨어 등록 신청서 작성을 해야하나요?

### ISSUE THREAD

**Issue by kjinwoo12** [entrylabs/entry-offline#53]
엔트리와 하드웨어를 이용한 콘텐츠를 개발하기 위해 준비를 하는 동안 궁금한 점이 생겨 문의드립니다.
하드웨어 등록 신청은 playentry.org에서 하드웨어 블록을 사용하기 위함인지, 모든 개발 절차에 다 필요한 것인지에 대한 질문입니다. playentry.org 사이트를 이용하지 않고, entry-offline 또는 entryjs 서버를 따로 열어둔 상태에서 엔트리와 하드웨어 콘텐츠 개발을 하기 위해서도 반드시 하드웨어 등록 신청을 해야합니까?

**Comment by kimorkim** [comment]
@kjinwoo12 기본적으로 하드웨어 등록신청서는 playentry.org에서 사용하기 위해 작성하는 내용입니다.
온라인에 해당 하드웨어가 반영되면 오프라인에 추후 반영이 자동으로 이루어 집니다.
다만, 사이트에 운영하실 예정이 없고 자체적으로 오프라인 수정을 통해서 처리하실 예정이라면 따로 등록신청서를 보내지 않으셔도 됩니다.
다만, 해당 수정을 통해서 배포 하실때 connect 재단이 공식적으로 지원하는 하드웨어 및 프로그램인것처럼 
홍보나 소개등의 오해의 소지가 없도록 해주시면 됩니다.
