### ISSUE TITLE
[Feature Request] 선택한 언어에 따라 디폴트 내장 오브젝트의 변경 가능

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#55]
안녕하세요? 

먼저 개도국 어린이를 위해 엔트리를 지역화 하는 것으로 계속 문의를 남겼었지요. 이번에도 관련한 문의인데요. 저희가 이 곳 현지인과 함께 지역에 맞는 오브젝트 이미지(예를 들어 이곳 전통 의상을 입은 오브젝트 등)의 제작이 거의 임박했는데요. 해당 이미지들을 넘겨드리면(pull-request에 의해) 엔트리 오프라인 버전에 기본 오브젝트(이미지)로 포함되 릴리즈 해주시는지요? 

저희가 제작할 이미지가 상당히 있는 편인데 그러면 제 생각엔 유저에게 항상 보여지는 전체 오브젝트 개수가 증가하게 될텐데 물론 그것도 어떤 면에선 유익이 있을 수 있고, 그것 말고 혹시 제목에 요청드린 바와 같이 해당 언어를 선택할 때 보여지는 디폴트 오브젝트들이 해당 언어에 맞는 것으로 변경되는 것은 어떨까요? 

의견을 부탁드립니다.
감사합니다.

**Comment by heavymedall** [comment]
@JeongJun-Lee 죄송합니다.
주셨던 문의에 대한 정책 논의가 길어져 답변이 늦어졌습니다.
말씀하신 오브젝트를 저희 엔트리 서비스에 기본 오브젝트로 포함하여 배포하는 것은 어려울 듯 싶습니다.

**Comment by JeongJun-Lee** [comment]
엔트리가 전 세계 어린이를 위한 국제적인 코딩툴이 되기 위해서는 국제화/지역화는 중요한 부분이라 생각되는데 개인적으로네 아쉽게 되었네요 조금 더 결정에 취지를 설명해 주시는 것도 가능할까요? 언어별로 오브젝트를 변경해 보여주는 기능 구현상의 어려움이나 개발 일정 상의 어려움이나 아니면 아예 그런 기능이 엔트리에 맞지 않는 것으로 결정하신 것인지 등등 구현상이나 개발 일정 상의 부분이면 저도 어느 정도는 시간을 내서 코딩 부분에서 기여를 할 여지도 있어서 여쭙니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 

- 엔트리 운영페이지는 엔트리 팀에서 관리하며, 웹 내 오브젝트는 오픈소스로 관리되지 않고 있습니다. 
- 언어 번역에 관해서는 내부에서도 개선 논의중입니다. 그러나 다양한 프로젝트가 하나의 언어팩을 공유하고 있어 쉽게 결정할 수 없는 점 양해바랍니다.
  - 또한 오프라인만 언어 파일을 수정하는 것이 release 에 반영되기 힘든 것은 일관성의 문제도 있습니다.

실 운영 페이지에 반영이 꼭 필요한 것이 아니라면 엔트리 오프라인 자체의 수정을 통해 필요한 곳에 전달할 수 있습니다.

현재 엔트리의 리소스부분을 따로 분리하고자 설계 변경중에 있으며, 정상적으로 반영되는 경우 원하시는 오브젝트 반영과 로직 수정을 직접 하실 수도 있을 것이라 생각됩니다.

**Comment by JeongJun-Lee** [comment]
@extracold1209 긍정적으로 검토해 주셔서 먼저 감사드립니다. 개도국의 인터넷 인프라 형평상 실 운영 페이지에 반영까지는 고려되지 않습니다. 온라인 상에서 직접 교육이 가능한 수준까지 인프라가 되려면 꽤 오랜 시간이 필요합니다. 그래서, 현재는 오프라인에서 활용/교육이 젤 큰 니즈이기 때문에 언어번역 논의하실 때 온라인/오프라인 언어추가에 대한 별도 프로세스를 고려하시면 좋겠다 추천드립니다.

**Comment by JeongJun-Lee** [comment]
@extracold1209 안녕하세요? 제가 지난 주 이웃국가(타지키스탄) 방문을 통해 스크래치보다 엔트리를 통한 교육의 유용성을 적극 홍보한 이후, 기존에 스크래치로 해오는 것을 엔트리로 바꾸자며 이웃국가에서도 엔트리의 교육과 도입에 큰 관심을 표해주셨고, 당장이라도 지역 초등학교에서 교육하고자 하여 러시아어/타지키스탄어의 번역을 시작했습니다. 번역 완료 후 여전히도 계속 오프라인용 새로운 신규언어 추가는 공식 버전에 추가되는 것을 기대할 수 없고, 로컬 PC상에서 커스텀 버전을 만들어서 활용해야 할까요?

**Comment by JeongJun-Lee** [comment]
@ViresseNisSJ @extracold1209 안녕하세요? 오픈소스인 스크래치를 기반으로 해서 아두이노 코딩과 파이썬 코딩을 추가한 커스텀 에디터를 만든 사례가 있습니다. 이미 알고 계실 수도 있는데요. 오픈소스 방식 언어번역 통해 빠르게 전 세계로 세력을 확장하고 있는 좋은 모델이라 한번 참고하시면 좋을 것 같아 소개합니다. 엔트리도 생각은 하고 계시겠지만 우선순위에 밀리고 있는 것 같은데, 제가 보기엔 아쉬워서 자꾸 말씀드리게 되는 것 같네요. 그럼, 세계 속의 엔트리로 되길 계속 응원합니다!

http://www.mblock.cc/docs/note-for-translators/#
https://crowdin.com/project/mblockpc
