### ISSUE TITLE
특정 오브젝트 이름의 경우 언어를 바꿔도 항상 한글로 보입니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#60]
첨부처럼 선택언어에 상관없이 항상 한글(운동하는 엔트리)로 보이는게 있습니다. 

![image](https://user-images.githubusercontent.com/11474775/45944781-cefeb000-c004-11e8-8763-bad4cded1ab6.png)

제가 우즈벡어 버전을 오브젝트를 추가하면서 sprites.json에 해당언어의 키/값을 추가했는데, 어떤 언어를 선택해도 위에 예처럼 항상 한글로만 보입니다. 어떻게 하면 선택 언어에 따라 오브젝트 이름이 바뀌나요?

{
    "_id":"56cb52e5fc051ddf4ba6110e",
    "__v":0,
    "name":"논",
    "user":"56b2f0052d7146c949202baa",
    "specials":[],"created":"2018-09-22T18:26:45.271Z",
    "sounds":[],
    "pictures":[
      {
        "_id":"53f335867414ccbd1641f7f1",
        "filename":"0004181c9e3783c401780d26b9c81c4d",
        "name":"논_1",
        "dimension":{"height":213,"width":226},
        "label":{"uz":"Non_1","en":"Non_1","ko":"논_1"}
      }
    ],
    "type":"_system_",
    "category":{"main":"food","sub":"food_others"},
    "label":{"uz":"Non","en":"Non","ko":"논"}

**Comment by extracold1209** [comment]
'운동하는 엔트리' 이슈는 스프라이트 목록 동기화 관련 문제였습니다.
과거 이슈 트래킹 결과 과거에 해결된 문제이나 스프라이트 목록이 오프라인에 업데이트 되지 않은 문제인데요.

스프라이트와 다국어는 현재 엔트리 운영사이트에서 그대로 받아서 사용중이기 때문에, 수동으로 작업해야 하는 번거로움이 있습니다.

그래서 스프라이트 및 다국어 적용에 문제가 있으며, 해당 프로세스는 추후 개선예정입니다.

**Comment by JeongJun-Lee** [comment]
엔트리 웹사이트에서 코딩화면에서 한국어가 아닌 언어로 변경 후 오브젝트 열기를 해보면 오브젝트의 이름이 오직 영어로만 보이고 있던데 결국 현재는 아직 오브젝트 이름들은 다국어 지원이 안되는 것으로 보이는데 맞나요? 추후 오브젝트 이름까지 다국어 지원하는 것을 고려하고 계신지 궁금합니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 

해당 이슈는 2.0.0 에서 해결되었으므로 close 하겠습니다.
현재 엔트리 내부에서 운영하는 오브젝트 명은  한/영 외에 존재하지 않습니다.
https://github.com/entrylabs/entryjs/pull/1214 이슈가 정상처리되면 오프라인의 DummyDB 데이터의 직접 수정된 결과가 정상적으로 반영될 것으로 예상됩니다.
