### ISSUE TITLE
소리 추가에서 각 소리의 분류 제목이 잘못되었습니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#61]
![image](https://user-images.githubusercontent.com/11474775/46282553-3da2b700-c58b-11e8-9c26-f3f8aa652dd6.png)

첨부와 같이 자연이란 카테고리 안에 악기라고 잘못보여지고 있습니다. 악기 카테고리는 별도로 있는데 말이지요.

**Comment by extracold1209** [comment]
스프라이트 및 사운드 데이터 관련 이슈의 경우, 이전에는 운영 서비스측의 데이터베이스를 일정주기로 export 하여 수동으로 오프라인에 데이터를 작업하는 방식으로 진행되었습니다.

또한 현재 기본 오프라인 데이터의 경우 최신화가 아주 오래전에 이루어진 것으로 판단됩니다.  
이 부분에 관하여 프로세스 개선이 있을 예정입니다.

이슈 클로즈 하겠습니다. 감사합니다.
