### ISSUE TITLE
계산 블록에 [몫/나머지] 블록 번역이 정상적으로 적용되지 않음

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#63]
계산 블록에 [10/10 의 몫(나머지)] 블록을 아래와 같이 변역했습니다.

  "CALC_quotient_and_mod_1": "",
  "CALC_quotient_and_mod_2": "/",
  "CALC_quotient_and_mod_3": "ning",
  "CALC_quotient_and_mod_4": "",
  "CALC_quotient_and_mod_sub_1": "bo'linma",
  "CALC_quotient_and_mod_sub_2": "qoldiq",

순서상 한글 번역하고 차이가 없는데, 한국어를 선택했을 때 보여지는 것처럼 [10/10 의 몫(나머지)] 로 보이는게 아니라 아래 그림처럼 순서가 [몫(나머지) / 10의 10] 라고 순서를 보여주며, 위에 번역의 순서를 어떻게 바꿔봐도 항상 몫(나머지) 부분이 순서상 젤 먼저에 옵니다.
![image](https://user-images.githubusercontent.com/11474775/47565611-88251280-d942-11e8-9aa2-947697d61613.png)

**Comment by extracold1209** [comment]
그 부분은 먼저 ko.js , en.js 를 봐주셔야 할 것 같습니다.
CALC_quotient_and_mod_1 등의 단어 파편들의 순서는 실제로는

"quotient_and_mod": "%1 %6 %3 %2 %5 %4" 와 같은 실제 템플릿 순서에 의해 결정됩니다.
이는 en.js 의 순서로, 템플릿을 찾지 못하면 english 를 default 로 사용하기 때문에 위와 같은 순서로 배정 된 것으로 예상됩니다.

단어조각 뿐 아니라 템플릿순서를 수정해 보시길 바랍니다.

**Comment by JeongJun-Lee** [comment]
네 그렇네요. "quotient_and_mod"의 순서를 조정했더니 정상적으로 보입니다. 그럼, 이슈를 닫을께요.
