### ISSUE TITLE
모든 코드 멈추기 블럭으로 모든 코드가 멈추지 않습니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#65]
![image](https://user-images.githubusercontent.com/11474775/48956016-68e5c900-ef72-11e8-9908-2a180196c323.png)

샘플로 해당 이미지처럼 코드를 짜고 실행시켜 보면 모든 코드 멈추기가 실행되었음에도 위쪽 화살표로 오브젝트를 움직이는게 계속 가능합니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 

이벤트의 순서는 아래와 같습니다.

실행하자마자 위쪽 코드뭉치가 실행됨 -> 10만큼 움직인 후 -> 동작중인 코드 멈추기

하지만 아래 코드뭉치는 현재 동작중인 코드가 아니고, 이벤트를 기다리고 있습니다.  
그러므로 코드멈추기는 이미 실행되어서 끝난 상태이고, 아래는 이벤트 발생으로 실행되는 것이죠.

그런의미로 위쪽 화살표를 두번 누르면 아래 코드뭉치는 두번 실행됩니다.

![default](https://user-images.githubusercontent.com/40051225/48988005-4caa7d80-f166-11e8-81d1-7c973de9329a.png)

위와 같이 실행하시면 정상동작을 확인하실 수 있습니다.

**Comment by prisml** [comment]
정상동작이 맞으므로 해당 이슈는 닫겠습니다.

**Comment by JeongJun-Lee** [comment]
위에 내용은 화살표 키로 오브젝트를 조정하는 작은 게임을 만들었는데, 게임이 특정 조건에서 끝나게 될 때 <모든 코드 멈추기>를 사용해서 전체 프로그램을 멈추게 하려했으나, 화살표 키가 계속 동작하길래 이슈라고 생각했습니다. 그렇다면, 이러한 이벤트 발생을 포함한 프로그램 전체를 완전히 종류하는 블럭은 없는 것인지요?

**Comment by prisml** [comment]
장면 전환으로 게임 종료를 표현하는 것은 어떨까요?

**Comment by JeongJun-Lee** [comment]
어떻게든 종료를 표현하는 것은 가능하겠지만, "모든 코드 멈추기" 라는 의미의 블럭을 접할 때 프로그램이 종료되는 것으로 자연스럽게 생각이 연결될 것 같은데, 모든 코드가 멈추는게 아니라 키보드 이벤트 수신에 대한 예외가 있다는 것은 미처 생각하기 어려운 부분이구요. 제 생각에는 블럭이름 이라던지 블럭실행 후 결과라든지 둘 중에 하나는 다시 한번 고민해 보셔야 할 필요가 있는 부분이 아닐까 하는 생각이 들었습니다.

**Comment by ViresseNisSJ** [comment]
@JeongJun-Lee 
[모든]코드 멈추기 블록은 블록의 실행을 멈추는 블록이며, 프로그램을 종료하는 블록이 아닙니다. 
프로그램 종료는 "정지하기" 버튼을 통해서만 가능하다는 점 참고 부탁드립니다.
블록 이름을 변경할 경우 다른 사용자에게 혼동을 줄 수 있으므로, 추후 블록 도움말에 블록 기능에 대해 혼동이 없도록 상세하게 작성해두도록 하겠습니다.
