### ISSUE TITLE
그림판에 상하뒤집기, 좌우뒤집기 버튼의 툴팁을 번역할 수 없습니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#66]
![image](https://user-images.githubusercontent.com/11474775/49326579-07c38400-f576-11e8-9d7d-1af27ec8496d.png)

모양 탭(그림판)에 하단에 위치한 상하뒤집기, 좌우뒤집기 버튼의 툴팁을 번역할 방법이 없는 것 같습니다. 별도의 언어파일에서 불러 오는게 아니라 소스 안에 fixed된게 아닌가 합니다.

**Comment by ViresseNisSJ** [comment]
@JeongJun-Lee 
해당 부분 내부에서도 인식하고 있으며, 내년 중에 Alt 태그에도 다국어를 적용할 예정할 예정입니다.

**Comment by extracold1209** [comment]
해당 문제는 최신 entryjs 워크스페이스에서 해결되었으므로 이슈 클로즈합니다.
