### ISSUE TITLE
[Feature Request] 만든 코드(=프로그램)를 한 개의 배포 가능한 실행파일로 만들어 주기

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#67]
개발도상국(이하 개도국)에선 인터넷 보급이 원활하지 않고 인터넷 사용료가 비싸서 오프라인 엔트리로 가르치고 배울 수 밖에 없는 이유가 존재합니다.

이곳 개도국에서 가르치다 보니, 많은 학생들의 요구가 자기가 만든 코드(곧 프로그램)을 다른 사람에게 줘서 자랑하고 싶은 것입니다. 선진국에서는 바로 인터넷을 통해 엔트리 웹사이트(play-entry.org)에 연결해 자기 작품을 공유하면 됩니다. 그러나, 개도국에서는요? 그것은 이 곳 현실에서는 상당히 어려운 이야기이며 앞으로도 그렇게 인터넷이 언제 보편화 될 지 먼 이야기 입니다. 하지만 내가 만든 걸 자랑하고 싶은 사람의 요구는 다 똑같지요. 그리고, 자기가 만든 코드를 한 개의 exe(원도우즈 OS기준)으로 만들어 다른 사람에게 주는게 가능하냐는 문의가 많습니다. 

이런 걸 구현하는 방법에 대해 제가 생각해 본 세 가지 아이디어는...
Electron 같은 것을 이용해 정말 실행가능 한 파일 한 개로 생성해 주는 방법과 아니면 사용자가 만든 코드를 표준 html5 포맷의 컨텐츠로 패키징해줘서 웹 브라우저 안에서 재생하는 일종의 독립된 html5 프로그램이 되는 방법, 마지막은 과거에 어도브사 플래시 컨텐츠들을 재생하기 위해서 브라우저에 내장된 플레이어가 아닌 별도의 독립된 플래시 플레이어가 있었던 것 처럼 엔트리로 만든 코드를 재생하긴 위한 별도의 플레이어를 만드는 것입니다.  

한 번 이런 제안에 대해 생각해봐 주시면 감사합니다^^

**Comment by ViresseNisSJ** [comment]
엔트리 오프라인 작품 파일을 인터넷이 없는 환경에서 실행시킬 수 있는 방법에 대해 검토해 보도록 하겠습니다.
다만, 개발 범위가 상당히 클것으로 예상되어 빠른 대응은 어렵다는 점 양해부탁드립니다.
개발이 되기 전까지는 작품 파일을 전달할 때 엔트리 오프라인 프로그램 설치파일을 함께 전달하는 방법을 추천드립니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 

엔트리 오프라인의 버전이 2.0.0 으로 신규배포 예정입니다.
리포지토리에는 코드가 완전히 변경되었으니 한번 이전 이슈들에 관해 확인 부탁드립니다.

또한 모든 이슈의 경우, 직접 처리가능한 경우 PR 을 올려주시면 코드리뷰 후 반영가능한 점 참고부탁드립니다.

이 이슈에 관해, 현재 엔트리 팀에서는 작업을 할 여력이 당장은 부족한 상황입니다.  
혹시 직접 개발이 가능한 상황일 때 참고가 될 만한 점을 말씀드리고자 합니다.

Entry.init 의 초기 옵션으로 type: 'minimize' 를 주면 실행 영역(스테이지) 만 나오는 모드로 엔트리를 실행할 수 있습니다.

이 코드는 [엔트리의 작품공유 영역](https://playentry.org/lany21/5c68cb6480f6faaabcc72f0b?returnUrl=https%3A%2F%2Fplayentry.org%2Fall%23!%2F%3Fsort%3Dupdated%26rows%3D12%26page%3D1#!/) 을 예시로 들 수 있습니다.

이를 활용하여 일렉트론 혹은 작품공유페이지와 유사한 웹을 만들 수 있지 않을까 생각됩니다.

**Comment by JeongJun-Lee** [comment]
@extracold1209 안녕하세요? 현장에서 지속적인 요구가 있어서 한번 시도해 보려고, 알려주신데로 [해당 코드](https://github.com/entrylabs/entry-offline/blob/e9969dd2b2e4c38d05e0222095f1e24dbb118597/src/renderer/components/workspace.tsx#L36)에서 'minimize'를 주고 실행시켜 보았으나, 다음과 같은 에러만 나오고 실제 언급하신 것처럼 작동하지는 않습니다. 어떻게 하면 좋을까요? 

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/11474775/204772301-f25865f8-bc90-4e74-8a3d-0c0e5b8e8db2.png">
