### ISSUE TITLE
하드웨어 연결시 아두이노 확장으로 열고 나타나는 블록들이 다국어 번역이 안됩니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#69]
아두이노 우노 확장 관련 8개의 블록들을 다음과 같이 다국어 번역했음에도 불구하고 첨부 이미지처럼 항상 영어로만 표기됩니다.

  "arduino_ext_get_analog_value": "Analog %1pin qiymat",
  "arduino_ext_get_analog_value_map": "%1 %2 ~ %3dan %4 ~ %5ga o'zgartir",
  "arduino_ext_get_ultrasonic_value": "Ultrasonic Trig %1pin Echo %2pin sensor qiymati",
  "arduino_ext_toggle_led": "Raqamli %1pin %2 %3",
  "arduino_ext_digital_pwm": "Raqamli %1pin %2ga sozla %3",
  "arduino_ext_set_tone": "Raqamli %1pin %2 nota %3 oktava %4 zarbadan chal %5",
  "arduino_ext_set_servo": "Raqamli %1pin servo %2 darajaga sozla %3",
  "arduino_ext_get_digital": "Raqamli %1pin qiymati",

![image](https://user-images.githubusercontent.com/11474775/51495465-4808eb00-1dde-11e9-835f-cc77578da9af.png)

버전: 1.6.13

**Comment by extracold1209** [comment]
@JeongJun-Lee 
안녕하세요.
현재 엔트리 오프라인이 엔트리 개편에 맞춰 전체적으로 개편에 들어가서 상세한 이슈를 처리해드리기 어렵습니다. 죄송합니다.
이전 몇가지 이슈에 대해 답변 드리고자 합니다.

엔트리 WS 에서 일어나는 대부분의 경우 (entryjs 에서 수정이 필요한 경우) 는
- 글자가 벗어나는경우 : css 문제로, 쉽게 적용하기 어렵습니다. 기획팀 논의와 모든 div 를 적절하게 커버해야 하기 때문입니다.

- 엔트리 프로젝트 전용 뷰어 개발 : 좋은 의견이긴 합니다만 일정상 내부논의가 필요할 것 같습니다.
- 연결 프로그램 열기 다국어 번역 불가 : 신규 엔트리 오프라인에서 처리되었습니다.
- 하드웨어 블록이 한/영 외 지원하지 않도록 개발되어있는지는 시간나는 대로 확인하도록 하겠습니다.

엔트리 오프라인 신규버전의 경우는 아직 개발중에 있으며, 현재 리포지토리는
https://github.com/extracold1209/entry_offline_new 입니다.
2월 배포에 운영 적용 예정입니다.

**Comment by JeongJun-Lee** [comment]
먼저 답변 감사드립니다. 하드웨어 블록이 한/영 외 지원하지 않는 문제는 먼저 좀 릴리즈 전이라도 어느 부분에서 제가 로컬에서 고쳐서 써볼 수 있을까요? 아두이노 확장보드를 사용해 수업을 진행하고 싶은데, 번역문제로 좀 어려움을 겪고 있어서요.

**Comment by extracold1209** [comment]
@JeongJun-Lee 

엔트리 프로젝트는 기본적으로 오픈소스이므로 개인적으로 고쳐 쓰는 것은 문제 없습니다.
수정된 코드를 entryjs 에 정식반영을 요청하는 경우라면 pull request 를 하실 수도 있습니다.

**Comment by JeongJun-Lee** [comment]
@extracold1209 네 그 때 답변 주셨을 때 "하드웨어 블록이 한/영 외 지원하지 않도록 개발되어있는지는 시간나는 대로 확인하도록 하겠습니다." 라고 해주셔서 혹시 찾으셨나 해서요. 제가 당장 우선 어디 부분 고쳐서 쓰면 되는지 알려주실 수 있으실까요?

**Comment by JeongJun-Lee** [comment]
디버깅을 통해 이유를 찾았습니다. 각 다국어 언어파일(jp.js, vn.js)안에 Lang.type="en" 으로 고정되어있기 때문입니다. 이를 각 언어에 맞게 변경하면 번역된 것으로 잘 나옵니다.
