### ISSUE TITLE
번역한 하드웨어 관련 블럭이 한 줄로 뭉쳐 표시됩니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#70]
안녕하세요? 먼저 아두이노 확장모드 번역문제 관련 #69번 이슈를 해결책을 적용했더니, 그 해당 이슈는 해결되나 다른 하드웨어 연결 후 생성된 블록들에서 아래와 같이 모든 블록이 한 열에 다 뭉쳐 표시되는 문제(ws가 깨지는?)가 발생하고 있습니다.

![image](https://user-images.githubusercontent.com/11474775/53029866-8fd96b80-348b-11e9-9fad-d25edffb874b.png)

**Comment by JeongJun-Lee** [comment]
에러로그 붙혀드립니다.

![image](https://user-images.githubusercontent.com/11474775/53033391-c5ce1e00-3492-11e9-9d17-9987a3323c92.png)

**Comment by extracold1209** [comment]
@JeongJun-Lee 

아직 확인된 것은 아니나, 기존 모든 하드웨어는 ko, en 만을 가지게 되어있습니다.
그러나 Lang type 을 세분화 하면서, ko, en 이 아닌 다른 타입의 언어 템플릿을 '모든 블록' 에서 찾게 되면서 발생한 문제일 수 있습니다.

entryjs 에 보면 하드웨어의 setLanguage 를 찾아서 Lang 오브젝트에 하드웨어 모듈 내 언어 템플릿을 주입하는 로직이 있는데요. 거기에 해당 Lang Type 의 템플릿을 찾을 수 없으면 en 을 기본값으로 가지게 만드는 등의 방어코드가 필요할 것 같습니다.

**Comment by JeongJun-Lee** [comment]
@extracold1209 네 언급하신 내용이 맞는거 같습니다. 각 하드웨어 파일에 존재한 것을 언어파일쪽에 중복 추가했더니 문제가 해결은 됩니다. 써드파티가 작성하는 하드웨어쪽 코드에도 다국어 지원에 대한 지원이 필요한 것 같습니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 

하드웨어 블록 번역에 있어, 직접 lang 파일을 수정하는것은 deprecated 된 방식입니다.
[Entry Docs](https://entrylabs.github.io/docs/guide/entryjs/2018-03-09-translate.html) 를 참고해주세요.

하드웨어 관련 코드 수정은 [entryjs](https://github.com/entrylabs/entryjs) 를 봐주시기 바랍니다.

그러나 임시적으로 lang 파일을 직접 수정하는 것도 상관은 없는데요.
https://github.com/entrylabs/entryjs/pull/1214 해당 이슈 적용 완료시 해당 문제는 해결될 것으로 보입니다.
