### ISSUE TITLE
1.6.x 버전에서 만든 엔트리 프로젝트를 2.0에서 실행할 수 없습니다. 그러나 온라인에서는 가능합니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#73]
1.6.x 버전에서 만든 엔트리 프로젝트를 2.0에서 실행할 수 없습니다. 그러나 온라인에서는 가능합니다. 온라인 사이트에서는 1.6 버전에서 만든 프로그램을 로드시 1.6=>2.0버전으로 자동 컨버전이 기능이 있나봅니다. 문제없이 보이고, 실행도 잘됩니다. 오프라인 버전도 그렇게 될 수 있도록 해주시면 감사합니다!
[flappy bird.ent.zip](https://github.com/entrylabs/entry-offline/files/2924748/flappy.bird.ent.zip)

**Comment by extracold1209** [comment]
@JeongJun-Lee 해당 이슈 재현에 필요한 프로젝트 전달 부탁드립니다.

**Comment by JeongJun-Lee** [comment]
@extracold1209 해당 이슈에 파일을 attach했습니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 2.0.2 버전 운영페이지에 업로드 되었습니다.
