### ISSUE TITLE
[문의] 하드웨어 연결창에 내용들도 번역이 가능한지요?

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#74]
![image](https://user-images.githubusercontent.com/11474775/53726217-5c391100-3e8f-11e9-85a9-c69ae655c6d9.png)

하드웨어 연결을 위해 별도로 열리는 창 안에 내용이 에디터 상에 영어/일본어 등 타국어로 선택되어 있음에도 항상 한글로만 보이던데 한글 외 다른 언어로 번역이 가능한지요?

**Comment by extracold1209** [comment]
@JeongJun-Lee 
엔트리 하드웨어의 번역은 OS 언어 (정확히는 chrome window의 navigator.language) 를 따르게 됩니다.  
또한 한/영 만 지원하고 있으며 다국어 지원 체계가 조금 다릅니다.

그래서 코드를 수정하기엔 수정사항이 많아서 일단 우선순위가 낮다는 점 양해부탁드립니다.

**Comment by JeongJun-Lee** [comment]
@extracold1209 네 일단 당장은 어렵다는 점 이해합니다. 공식으로 지원되기 전까지 당장은 커스텀으로 버전 만들어 사용해야 할 것 같고, 언뜻보기에는 entry-hw를 직접 고쳐 사용하면 될 것 같은데, 해보고 안되면 또 추후 문의드리겠습니다. 감사합니다.

**Comment by JeongJun-Lee** [comment]
제가 고쳐서 커스텀 버전에서 번역가능 하게 해서 사용 중인데, 혹시 반영 의사가 있으신가 하여 관련 코드를 pull-request 합니다. 감사합니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 
entry-hw develop 브랜치에서는 이제 app/src/renderer/js/translation.json 파일의 수정을 통해 다국어 추가가 가능합니다.

하지만 현재 접속한 크롬의 locale 에 따라 자동 변경되고, 외부에서 언어를 선택하는 기능은 아직 제공하지 않으니 참고 부탁드립니다.

**Comment by JeongJun-Lee** [comment]
크롬 로케일은 저도 한국인이지만 한국어말고 영어로 놓고 사용 중이고, 딱히 이곳에서도 우즈벡이지만 주로 대다수는 러시아어 로케일로 놓고 쓰기 때문에 로케일로 언어가 정해지는 것보다 에디터 상에 선택한 언어를 기반으로 언어가 정해지면 좋겠습니다.

**Comment by JeongJun-Lee** [comment]
안녕하세요? 해당 이슈가 여전히도 개도국에서는 필요한 상황이라 재오픈으로 시간이 걸리더라도 Feature requst로 처리될 가능성은 없는지 재문의 합니다. 현재는 어쩔 수 없이 언어를 특정 언어로 강제하는 커스텀 버전을 빌드해 이곳 개도국(우즈베키스탄)에 배포하고 있으나, 임시적인 방편이고 궁극적으로는 엔트리에서 구현이 되어야 하는 부분이지요. 
당시 2년전 해당 피처는 우선순위는 낮다고 하셨지만, 2년이 지난 현 시점에도 아직 적용이 안되고 있네요. 한국과 기타 선진국만 생각하면 우선순위는 당연히 낮겠지만, 커넥트 재단이 추구하는 개도국까지 포함한 전세계 보편적 공헌으로 고려해주시면 어떨까요? 

이와 관련해 제가 [PR](https://github.com/entrylabs/entry-hw/pull/214)도 만들어 오프라인에서 선택한 언어를 우선순위로 적용하고 없으면 navigator.locale을 fallback으로 하는 것을 제안드렸는데, 이마져도 적용이 안되서 아쉬움이 많이 남네요. 감사합니다.
