### ISSUE TITLE
모양탭에서 파일, 편집 메뉴가 번역이 되지 않습니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#75]
![image](https://user-images.githubusercontent.com/11474775/54081901-b83be380-432e-11e9-99a9-489372c37932.png)

첨부 이미지처럼 아래와 같이 번역을 적용했음에도 번역어로 표시되지 않습니다.

"painter_file": "Fayl ▼",
"painter_edit": "Tahrir ▼",

그러나, 일본어의 경우는 번역이 정상적 동작합니다.

**Comment by extracold1209** [comment]
entry-js 프로젝트 내 painter.js 에서 확인해본 결과,
각각 Lang.Menus.offline_file, Lang.Menus.offline_edit 을 참조하고있으며 정상변경 확인하였으므로 클로즈합니다.
