### ISSUE TITLE
Bring All to Front 메뉴가 번역할 방법이 없음

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#78]
![image](https://user-images.githubusercontent.com/11474775/54082521-af500f80-4338-11e9-962f-17b9fd6a6a5a.png)

다른 서브메뉴들은 번역이 가능하나 Bring All to Front 메뉴는 번역할 방법이 없음

**Comment by extracold1209** [comment]
@JeongJun-Lee 

이에 대한 다국어 가이드가 없는 상태인데, 요청 가능할까요?

**Comment by extracold1209** [comment]
Bring All to Front 에 대한 번역 요청을 하였으나 이슈 진행상황이 없어 클로즈합니다.
