### ISSUE TITLE
엑셀 추출에 실패했습니다 / 성공했습니다 를 번역할 수 없습니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#80]
![image](https://user-images.githubusercontent.com/11474775/54176751-d5e58600-44b1-11e9-99b7-ca4c5bc79159.png)

언어파일을 사용하지 않고 코드상에 직접 적혀져 있어 번역방법이 없습니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 
2.0.4 버전에서 다국어 적용하도록 하겠습니다.

**Comment by extracold1209** [comment]
해당 문구의 경우 본 엔트리에 존재하지 않으며, 제가 임의로 추가한 사항이라 우선순위에서 밀려있습니다.
추가 완료시 이슈 처리하도록 하겠습니다.

**Comment by extracold1209** [comment]
엑셀 추출에 관한 알림 로직은 웹 로직과 동일하게 맞추기 위해 삭제되었으므로, 종료합니다.
