### ISSUE TITLE
외국어(영어 등) 동작 환경에서 오브젝트를 추가하면 영어가 아닌 한글 이름으로 등록됩니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#81]
외국어(영어 등) 동작 환경에서 오브젝트를 추가하면 오브젝트 추가화면에서 오브젝트 이름은 영어로 잘 표기가 됩니다. 그러나, 막상 추가되고 난 결과는 영어이름 아닌 한글이름으로 다시 재변환되어 한글이름으로 보입니다. 오브젝트 뿐만 아니라 소리를 추가해도 그렇습니다. 엔트리 1.6버전에서는 문제가 없습니다. 2.0에서 발생하는 문제입니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 
수정커밋 : https://github.com/entrylabs/entry-offline/commit/5c8556686e2ffa9ca39edb22dac80ea4d98b229e

3월 배포에 반영하도록 하겠습니다.

**Comment by extracold1209** [comment]
반영 완료로 이슈 close 합니다.
