### ISSUE TITLE
모양탭에서 모양추가 버튼 눌렀을 때 오브젝트 창이 뜨지않습니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#83]
맥용 빌드에서는 괜찮은데, 윈도우즈에서 빌드해서 만든 버전에서 발생하는 문제입니다.
에러 로그는 다음과 같습니다.

![image](https://user-images.githubusercontent.com/11474775/55293878-c902e500-5414-11e9-941e-325bb22f34cf.png)

**Comment by JeongJun-Lee** [comment]
안녕하세요? 바쁘시겠지만, 디버깅이 쉽지 않아서요. 혹시 어떤 문제라고 생각하시는지 힌트를 좀 주실 수 있으실까요?

**Comment by extracold1209** [comment]
'nav' of undefined 는 엔트리의 다른 라이브러리에서 발생하는 문제로 보입니다.

- bower_components, node_modules 삭제
- package-lock.json (yarn 사용시 yarn.lock) 삭제

이후 bower install 과 yarn (npm install) 재실행 해보시길 바랍니다.

테스트한 브랜치는 마스터입니다.

**Comment by JeongJun-Lee** [comment]
네 말씀하신대로 다 지우고 첨부터 다시 clean build 했더니 괜찮네요; close하겠습니다. 감사합니다.

**Comment by JeongJun-Lee** [comment]
참고로 여러 버전을 동시에 실행할 경우, 캐시파일에 의해 서로 영향을 받을 수 있어서 c:/Users/user_id/AppData/Roaming/Entry 를 지우고 실행시켜야 정상동작합니다.
