### ISSUE TITLE
How do I add new images in the source code?

### ISSUE THREAD

**Issue by KeyKrusher** [entrylabs/entry-offline#85]
How do I add in my own assets to the program directly without having to upload them?

**Comment by extracold1209** [comment]
1. update src/renderer/resources/db/[dummyDBname].json

```json
{
   "label":{
      "ko":"커서(2)_1",
      "en":"Cursor(2)_1"
   },
   "category":{
      "sub":"",
      "main":"interface"
   },
   "dimension":{
      "height":256,
      "width":218
   },
   "type":"_system_",
   "specials":[

   ],
   "filename":"e1928107205ed63d1644c43740f87909",
   "name":"커서(2)_1"
}
```

2. save real asset to src/renderer/resources/uploads

- the path below 'uploads' will be first four characters of 'filename' property
  - for example, filename's first 4 char is 'e192', directory path will be 'uploads/e1/92'

3-1. image object
directory structure is  
ㄴ image/[filename].png  
ㄴ thumb/[filename].png

3-2. sound object
sound is located directly.
ㄴ 'uploads/e1/92/[soundfilename].png
