### ISSUE TITLE
러시아어 번역 중에 있습니다. 러시아어 알파벳 사이 자간이 영어보다 현저히 넓네요.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#86]
블록명이 더 짧은 단어로 만드는 것을 찾아보기도 해야겠지만, 영어 알파벳 자간과 비교해 러시아어 알파벳 사이 자간이 영어보다 현저히 넓은데요. 폰트 라이센스 때문에 아무 것이나 넣는게 문제가 되나요? 혹시 폰트문제를 어떻게 풀면 좋을지요? 러시아어 번역이 되면 러시아어 사용 언어권이 상당하기 때문에 엔트리 국제화에 큰 도움이 될 것으로 예상합니다만... 

![image](https://user-images.githubusercontent.com/11474775/57875557-ab56d700-782c-11e9-8c71-9ef41412b5b5.png)

**Comment by kimorkim** [comment]
일단 무료로 풀려있는 폰트인 Noto Sans등의 웹폰트 계열사용에는 문제가 없을것 같습니다.
해당 폰트로 문제가 해결이 안되면 일단은 css로 처리가 불가피 해보입니다.

자간 및 장평조절, word-wrap을 통한 줄바꿈, font-weight조절, font-size조절등으로 처리를 해야 할것 같습니다.

**Comment by JeongJun-Lee** [comment]
그렇다면 첨부 이미지처럼 블록종류를 표기하는 이름에 경우 어디에서 고쳐야 하는지요?

**Comment by kimorkim** [comment]
카테고리는 entryjs 의 less파일에 내용이 들어 있습니다.
다만, css특성상 override가 가능하므로 덮어 쓰기를 하셔도 가능합니다.
![image](https://user-images.githubusercontent.com/5179851/57906273-65ddec80-78b4-11e9-9cec-a3371b686dae.png)

**Comment by JeongJun-Lee** [comment]
언급하신데로 NotoSansBold 폰트로 바꿔서 자간이 좁혀져서 그 폰트로 사용하려고 합니다. 다만, 빌드상에 불편한 점은 entryjs도 커스텀 빌드를 해서 entry-offline에서 포함시켜 릴리즈 해야 되는데, entry-hw와 달리 소스코드를 그대로 쓰는 것이 아니라, 매우 불편하네요;;; 

커스텀 entryjs를 bower.json에서 설정하는 것 만으로 자동화할 수 있는게 아니라,
https://entrylabs.github.io/docs/guide/entry-offline/2018-10-30-custom_project.html#entryjs-%EB%B0%98%EC%98%81%ED%95%98%EA%B8%B0 에 언급된데로 entryjs 구조를 매번 메뉴얼로 구조를 만들어줘야 한다는 것은 너무 불편해 보입니다.

**Comment by kimorkim** [comment]
일단 entryjs수정이 없으시다면 `bower install entry-js`로 entryjs 번들파일이 받아 집니다.
문서는 내용은 entryjs수정을 하신다는 가정하에 내용인상태입니다.
로컬에서 수정하실때 좀더 편하게 수정을 하시는 방법은 `bower link` 기능을 활용하시거나 
entryjs소스자체를 bower_component안에 clone받으셔서 개발하시는 방법이 있습니다.
