### ISSUE TITLE
[2.0.x] 배경 오브젝트의 수정이 안됩니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#87]
![image](https://user-images.githubusercontent.com/11474775/57965556-28826900-795f-11e9-8739-3f0cbc42d2d1.png)
첨부에서 보는 바와 같이 1.6.x버전에서는 배경 위에 새로운 그림을 추가하거나 등등 해서 자유로운 수정이 가능하였으나, 마우스 좌표가 X:NaN, Y:NaN 처럼 표시되면서 전혀 어떠한 수정도 가능하지 않습니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 
재현순서가 어떻게되나요?

**Comment by JeongJun-Lee** [comment]
모양탭에 놓은 상태로 새 장면을 추가=> 우측 편집화면으로 커서 이동시 X:NaN, Y:NaN 가 표시되고, 이후로는 다시 정상적인 어떤 오브젝트를 선택한다해도 계속 X:NaN, Y:NaN 상태로 보이면서 편집이 되지 않습니다.

**Comment by extracold1209** [comment]
@JeongJun-Lee 

저희가 그림판 라이브러리로 사용중인 literallycanvas 의 문제로, 현재 표기중인 그림판 영역이 작아서 발생한 문제입니다.

현재 내부적으로 그림판의 리뉴얼이 예정되어있어 그 전까지는 known-issue 로 남아있습니다.
정상적인 편집을 위해서는 충분한 화면 공간을 먼저 확보한 후 사용하셔야 할 것 같습니다.

리뉴얼 후에는 발생하지 않을 문제이므로 해당 이슈는 close 하도록 하겠습니다.
