### ISSUE TITLE
색상 설정 화면의 단어들을 번역할 방법이 없습니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-offline#88]
![image](https://user-images.githubusercontent.com/11474775/57968330-27166800-7982-11e9-9891-d5428036fa45.png)
해당 화면에 단어들을 번역할 방법이 없습니다.

**Comment by kimorkim** [comment]
일단 사용하신 위젯은 entry-tool라는 레포지토리에 공개되어 있습니다.
주소 : https://github.com/entrylabs/entry-tool
현재 다국어 적용이 안되어 있음이 확인되었습니다.
이 부분은 빠르게 수정할 예정입니다.
