### ISSUE TITLE
ERROR in ./src/renderer/renderEntry.js

### ISSUE THREAD

**Issue by hayanggames** [entrylabs/entry-offline#89]
빌드를 하면 오류가 납니다.

Ubuntu 19.04
Node.JS v10.16.0
NPM v6.9.0
입니다.

> entry@2.0.7 webpack:dev /home/thoratica/entry-offline
> cross-env NODE_ENV=development webpack

Hash: 788d0737309e868b8beffeba0c9f56ee1c344a11
Version: webpack 4.32.2
Child
    Hash: 788d0737309e868b8bef
    Time: 11856ms
    Built at: 2019-05-30 9:24:37 PM
                 Asset      Size  Chunks             Chunk Names
        main.bundle.js  3.21 MiB    main  [emitted]  main
    main.bundle.js.map  3.75 MiB    main  [emitted]  main
    Entrypoint main = main.bundle.js main.bundle.js.map
    [./src/main.js] 2.89 KiB {main} [built]
    [./src/main/blockConverter.js] 5.72 KiB {main} [built]
    [./src/main/commonUtils.js] 2.64 KiB {main} [built]
    [./src/main/constants.js] 4.02 KiB {main} [built]
    [./src/main/electron/commandLineResolver.js] 1.69 KiB {main} [built]
    [./src/main/electron/globalShortCutRegister.js] 396 bytes {main} [built]
    [./src/main/fileUtils.js] 7.58 KiB {main} [built]
    [./src/main/ipcMainHelper.js] 9.5 KiB {main} [built]
    [./src/main/mainUtils.js] 42 KiB {main} [built]
    [./src/main/views/aboutWindowManager.js] 1.37 KiB {main} [built]
    [./src/main/views/hardwareWindowManager.js] 2.5 KiB {main} [built]
    [./src/main/views/mainWindowManager.js] 5.33 KiB {main} [built]
    [crypto] external "crypto" 42 bytes {main} [built]
    [electron] external "electron" 42 bytes {main} [built]
    [path] external "path" 42 bytes {main} [built]
        + 436 hidden modules
Child
    Hash: feba0c9f56ee1c344a11
    Time: 10352ms
    Built at: 2019-05-30 9:24:35 PM
                   Asset      Size  Chunks             Chunk Names
          init.bundle.js  5.96 MiB    init  [emitted]  init
      init.bundle.js.map  2.02 MiB    init  [emitted]  init
        render.bundle.js   3.9 MiB  render  [emitted]  render
    render.bundle.js.map  2.64 MiB  render  [emitted]  render
    Entrypoint init = init.bundle.js init.bundle.js.map
    Entrypoint render = render.bundle.js render.bundle.js.map
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {init} {render} [built]
    [./src/renderer/helper/entry/entryModalHelper.js] 49.6 KiB {init} {render} [built]
    [./src/renderer/helper/importToggleHelper.js] 4.16 KiB {init} [built]
    [./src/renderer/helper/ipcRendererHelper.js] 8.72 KiB {init} {render} [built]
    [./src/renderer/helper/rendererUtils.js] 8.07 KiB {init} {render} [built]
    [./src/renderer/helper/storageManager.js] 3.73 KiB {init} {render} [built]
    [./src/renderer/initEntry.js] 1.39 KiB {init} [built]
    [./src/renderer/nativeMenu.js] 3.45 KiB {init} [built]
    [./src/renderer/reducers/index.js] 352 bytes {render} [built]
    [./src/renderer/renderEntry.js] 701 bytes {render} [built]
    [./src/renderer/resources/lang sync recursive ^\.\/.*\.json$] ./src/renderer/resources/lang sync ^\.\/.*\.json$ 247 bytes {init} [built]
    [./src/renderer/resources/modal/app.js] 567 KiB {init} {render} [built]
    [./src/renderer/resources/static.js] 772 bytes {init} [built]
    [./src/renderer/resources/static_mini.js] 2.79 KiB {init} [built]
    [./src/renderer/store.js] 748 bytes {render} [built]
        + 144 hidden modules
    
    ERROR in ./src/renderer/renderEntry.js
    Module not found: Error: Can't resolve 'components/Index.jsx' in '/home/thoratica/entry-offline/src/renderer'
     @ ./src/renderer/renderEntry.js 7:0-41 19:25-30
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! entry@2.0.7 webpack:dev: `cross-env NODE_ENV=development webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the entry@2.0.7 webpack:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thoratica/.npm/_logs/2019-05-30T12_24_37_413Z-debug.log

**Comment by extracold1209** [comment]
@hayanggames 
코드를 수정하셨나요? src/renderer/renderEntry.js 의 import 구문에서,
./components/Index.jsx 가 아닌 components/Index.jsx 를 찾고있습니다.

**Comment by hayanggames** [comment]
@extracold1209 뭔 문제가 있나 해서 바꿔 봤습니다.
그 전에도 안됐어요

**Comment by extracold1209** [comment]
@hayanggames 그전 에러는 다른 에러일 것으로 보입니다.

**Comment by hayanggames** [comment]
@extracold1209 그 전 에러도
Module not found: Error: Can't resolve './components/Index.jsx' in '/home/thoratica/entry-offline/src/renderer'
 @ ./src/renderer/renderEntry.js 7:0-41 19:25-30

였습니다.

**Comment by extracold1209** [comment]
@hayanggames 좀 더 상세한 개발환경 / 재현방식이 필요합니다.

**Comment by hayanggames** [comment]
@extracold1209 윈도우로 하니 됐네요
