### ISSUE TITLE
엔트리 오프라인 기존 함수 삭제 방법

### ISSUE THREAD

**Issue by minominium** [entrylabs/entry-offline#94]
안녕하세요.

엔트리와 햄스터 로봇을 사용해 블록코딩 수업을 진행하는 중,

여쭙고 싶은 것이 생겨 방문해 Issue를 남기게 되었습니다.

현재 엔트리 오프라인에는 다양한 블록 및 명령들이 존재하는데,

저와 같이 하드웨어 프로그래밍 용으로 사용하는 경우 필요없는 기능이 상당히 많이 존재합니다.

특히 기존 엔트리에 존재하는 '소리', '움직임' 등의 카테고리의 경우,

하드웨어에서 사용하는 함수 내용과 비슷하게 표기된 경우가 많아 학생들이 헷갈려 하거나,

심한 경우 수업 진행에 차질이 생기는 경우가 있습니다.

정리하면, 엔트리 오프라인에서 제공 중인 기존 함수와 카테고리,

리소스 파일 등이 필요없는 경우, 엔트리 오프라인 프로그램 자체를 커스텀 빌드 해야하는지,

아니면 따로 삭제할 방법이 있는지에 대해서 여쭤보고 싶습니다.

감사합니다. 즐거운 하루 보내세요.

**Comment by kimorkim** [comment]
@minominium 
오프라인에서 해당 카테고리를 제거하는 기능은 따로 제공하지 않습니다.
따로 빌드를 진행하셔야 하구요.
만약 축소된 버전으로도 만족하신다면 교과형 모드로 진행하시면 기본형보다는 줄어든 블록들을 이용하실수 있습니다.

**Comment by minominium** [comment]
옙 빠른 답변 감사드립니다.

항상 고생 많으십니다:)
